<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'hmerritt\\' => array($vendorDir . '/hmerritt/imdb-api/src'),
    'PHPHtmlParser\\' => array($vendorDir . '/paquettg/php-html-parser/src/PHPHtmlParser'),
    'Filebase\\' => array($vendorDir . '/tmarois/filebase/src'),
);
