<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2c8c500ad4a417ec06cbb500a1b001d3
{
    public static $prefixLengthsPsr4 = array (
        'h' => 
        array (
            'hmerritt\\' => 9,
        ),
        'P' => 
        array (
            'PHPHtmlParser\\' => 14,
        ),
        'F' => 
        array (
            'Filebase\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'hmerritt\\' => 
        array (
            0 => __DIR__ . '/..' . '/hmerritt/imdb-api/src',
        ),
        'PHPHtmlParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/paquettg/php-html-parser/src/PHPHtmlParser',
        ),
        'Filebase\\' => 
        array (
            0 => __DIR__ . '/..' . '/tmarois/filebase/src',
        ),
    );

    public static $prefixesPsr0 = array (
        's' => 
        array (
            'stringEncode' => 
            array (
                0 => __DIR__ . '/..' . '/paquettg/string-encode/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2c8c500ad4a417ec06cbb500a1b001d3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2c8c500ad4a417ec06cbb500a1b001d3::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit2c8c500ad4a417ec06cbb500a1b001d3::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit2c8c500ad4a417ec06cbb500a1b001d3::$classMap;

        }, null, ClassLoader::class);
    }
}
