<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'hmerritt/imdb-api' => array(
            'pretty_version' => 'v1.1.7',
            'version' => '1.1.7.0',
            'reference' => 'b9a335178bd5ba169bee4975fc53842167b8b9d5',
            'type' => 'project',
            'install_path' => __DIR__ . '/../hmerritt/imdb-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paquettg/php-html-parser' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'reference' => '668c770fc5724ea3f15b8791435f054835be8d5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paquettg/php-html-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paquettg/string-encode' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'a8708e9fac9d5ddfc8fc2aac6004e2cd05d80fee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paquettg/string-encode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tmarois/filebase' => array(
            'pretty_version' => 'v1.0.24',
            'version' => '1.0.24.0',
            'reference' => 'b660650472362e45f78d97cb395f09889196d164',
            'type' => 'package',
            'install_path' => __DIR__ . '/../tmarois/filebase',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
